server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    # Index par défaut pour Symfony
    index index.php;

    location / {
        # Essayer de servir le fichier directement, sinon passer à index.php
        try_files $uri /index.php$is_args$args;
    }

    # Passe les requêtes PHP à PHP-FPM
    location ~ \.php$ {
        fastcgi_pass api:9000; # <--- Le nom du service Docker Compose et le port
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    # Cacher l'accès aux fichiers sensibles
    location ~ /\.(ht|svn|git) {
        deny all;
    }
}